version: '3'
services:
  mysql:
    image: mysql:5.7
    container_name: ${APP_NAME}-mysql
    volumes:
       - './db:/var/lib/mysql'
    environment:
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
    restart: always
    ports:
      - '3306:3306'

  wordpress:
    image: wordpress
    container_name: ${APP_NAME}-wordpress
    ports:
      - '80:80'
    volumes:
      - ./wp:/var/www/html
    depends_on:
      - mysql
    restart: always
    environment:
      WORDPRESS_DEBUG: 1
      WORDPRESS_DISPLAY_ERRORS: 1
      WORDPRESS_DB_HOST: ${DB_HOST}
      WORDPRESS_DB_USER: ${DB_USER}
      WORDPRESS_DB_PASSWORD: ${DB_PASSWORD}
      WORDPRESS_DB_NAME: ${DB_NAME}
      WORDPRESS_DEBUG: ${WP_DEBUG}
      WORDPRESS_DEBUG_DISPLAY: ${WP_DEBUG_DISPLAY}
      WORDPRESS_DEBUG_LOG: ${WP_DEBUG_LOG}